import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import SideBar from './components/SideBar'
import HeaderBar from './components/HeaderBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='w-full h-screen bg-gray-100'>
        <div  className="flex h-screen ">
          <div className='m-4 w-64 flex-auto lg:flex-none shadow-2xl '>
            <SideBar/>
          </div>
          <div className=' m-4 ml-1 w-full flex-grow '>
            <div className='h-full flex flex-col' >
              <div className='border-b-2 h-16 flex-none' >
                <HeaderBar />
              </div>
              <div className='mt-2 flex-grow h-full '>
                {children}
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}
